@echo off
setlocal enabledelayedexpansion

echo ========================================================
echo        Starminer Music Replacer Mod Tool
echo ========================================================
echo.

:: Check for Python
python --version >nul 2>&1
if %errorlevel% neq 0 (
    echo Error: Python is not installed or not in your PATH.
    echo Please install Python 3 and try again.
    pause
    exit /b 1
)

:: Setup Original Assets
echo Checking original assets...
python "%~dp0setup_assets.py"
if %errorlevel% neq 0 (
    echo Error: Setup of original assets failed.
    pause
    exit /b 1
)

:: Run Python Patching Script
echo.
echo Running patch_audio.py...
python "%~dp0patch_audio.py"
if %errorlevel% neq 0 (
    echo Error: Patching audio files failed.
    pause
    exit /b 1
)

:: Run UnrealPak
echo.
echo Packaging staged files with UnrealPak...
set "unrealpak=%~dp0Engine\Binaries\Win64\UnrealPak.exe"
if not exist "!unrealpak!" (
    set "unrealpak=%~dp0bin\UnrealPak.exe"
)
if not exist "!unrealpak!" (
    set "unrealpak=%~dp0UnrealPak.exe"
)
if not exist "!unrealpak!" (
    set "unrealpak=C:\Program Files\Epic Games\UE_4.27\Engine\Binaries\Win64\UnrealPak.exe"
)

set "pak_out=%~dp0..\game\ILLSpace\Content\Paks\pakchunk0-WindowsNoEditor_P.pak"

set "crypto_json=%~dp0crypto.json"
if not exist "!crypto_json!" (
    set "crypto_json=%~dp0..\game\crypto.json"
)

set "response_txt=%~dp0response.txt"

if not exist "!unrealpak!" (
    echo Error: UnrealPak.exe not found at "!unrealpak!"
    echo Please install Unreal Engine 4.27 or place UnrealPak.exe inside this folder.
    pause
    exit /b 1
)

if not exist "!crypto_json!" (
    echo Error: crypto.json not found in ModTool or game directory!
    pause
    exit /b 1
)

if not exist "!response_txt!" (
    echo Error: response.txt was not generated by patch_audio.py.
    pause
    exit /b 1
)

:: Clean old patch pak file first
if exist "!pak_out!" (
    del /f /q "!pak_out!"
)

:: Package
"!unrealpak!" "!pak_out!" -Create="!response_txt!" -cryptokeys="!crypto_json!" -encrypt -encryptindex -ddc=noshared
if %errorlevel% neq 0 (
    echo Error: Packaging failed with UnrealPak.
    pause
    exit /b 1
)

:: Clean up local loose files in the game directory to avoid overrides
echo.
echo Cleaning up local loose files from game directory to ensure pak override...
set "loose_dir=%~dp0..\game\ILLSpace\Content\Audio\Music\SoundWaves"
if exist "!loose_dir!" (
    rmdir /s /q "!loose_dir!"
    echo Removed loose files from !loose_dir!
)

echo.
echo ========================================================
echo SUCCESS: Patch pak successfully generated and installed!
echo You can now launch Starminer.
echo ========================================================
echo.
pause
